CREATE TABLE people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) not null,
  last_name varchar(255) not null,
  birthdate date not null,
  
  PRIMARY KEY (id)
);
CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title varchar(100) not null,
  description varchar(255) not null,
  created_at datetime not null,
  owner INTEGER,
  
  PRIMARY KEY (id),
  FOREIGN KEY (owner) REFERENCES people(id)
);
INSERT INTO people (id, name, last_name, birthdate) VALUES (1, 'Tomas', 'Arango', '2000-01-22');
INSERT INTO people (id, name, last_name, birthdate) VALUES (2, 'Andres', 'Lora', '2000-06-12');

INSERT INTO posts (id, title, description, owner, created_at) 
      VALUES (1, 'Mi first post', 'This first post is all about my idea on computation.', 1, '2000-06-12 14:23:43');
INSERT INTO posts (id, title, description, owner, created_at) 
      VALUES (2, 'Mi second post', 'I looked on that issue and could not get a real answer buddy.', 1, '2000-02-25 09:17:38');
INSERT INTO posts (id, title, description, owner, created_at) 
      VALUES (3, 'Mi third post', 'That island has great views.', 1, '2000-08-21 17:01:12');


